
DROP DATABASE hoteldb;
CREATE DATABASE hoteldb;

USE hoteldb;

DROP TABLE IF EXISTS hoteldb.buzon;
DROP TABLE IF EXISTS hoteldb.info_hotel;
DROP TABLE IF EXISTS hoteldb.detalle_reserva;
DROP TABLE IF EXISTS hoteldb.venta_producto;
DROP TABLE IF EXISTS hoteldb.reservas;
DROP TABLE IF EXISTS hoteldb.facturas;
DROP TABLE IF EXISTS hoteldb.compra_producto;
DROP TABLE IF EXISTS hoteldb.compras;
DROP TABLE IF EXISTS hoteldb.proveedores;
DROP TABLE IF EXISTS hoteldb.categorias_producto;
DROP TABLE IF EXISTS hoteldb.productos;
DROP TABLE IF EXISTS hoteldb.habitaciones;
DROP TABLE IF EXISTS hoteldb.clientes;
DROP TABLE IF EXISTS hoteldb.tipos_documento;
DROP TABLE IF EXISTS hoteldb.tipos_reserva;
DROP TABLE IF EXISTS hoteldb.estados_habitacion;
DROP TABLE IF EXISTS hoteldb.estados_reserva;
DROP TABLE IF EXISTS hoteldb.administradores;


CREATE TABLE buzon(

ID_MENSAJE INT(4) NOT NULL,

NOMBRE_REMITENTE VARCHAR(30) NOT NULL,

APELLIDO_REMITENTE VARCHAR(30) NOT NULL,

EMAIL VARCHAR(60) NOT NULL,

ASUNTO VARCHAR(20) NOT NULL,

MENSAJE VARCHAR(256) NOT NULL,

PRIMARY KEY (ID_MENSAJE)

) ENGINE = MyISAM;


CREATE TABLE info_hotel(

ID_INFO     INT(1) NOT NULL,

NOMBRE_HOTEL VARCHAR(30) NOT NULL,

TELEFONO_HOTEL VARCHAR(15) NOT NULL,

EMAIL_HOTEL VARCHAR(50) NOT NULL,

RAZON_SOCIAL VARCHAR(30),

NIF VARCHAR(30),

DEPARTAMENTO_HOTEL VARCHAR(30) NOT NULL,

MUNICIPIO_HOTEL VARCHAR(30) NOT NULL,

DIRECCION_HOTEL VARCHAR(30) NOT NULL,

PRIMARY KEY (ID_INFO)

) ENGINE = MyISAM;


CREATE TABLE administradores (

ID_ADMINISTRADOR INT(4) NOT NULL,

NOMBRE_ADMINISTRADOR VARCHAR(30) NOT NULL,

CONTRASENA VARCHAR(256) NOT NULL,

PRIMARY KEY (ID_ADMINISTRADOR)

) ENGINE = MyISAM;


CREATE TABLE tipos_documento(

ID_TIPO_DOCUMENTO INT(4) NOT NULL,

NOMBRE_TIPO_DOCUMENTO VARCHAR(30) NOT NULL

) ENGINE = MyISAM;


CREATE TABLE clientes(

ID_CLIENTE INT(4) NOT NULL,

ID_TIPO_DOCUMENTO INT NOT NULL,

DOCUMENTO_CLIENTE VARCHAR(30) NOT NULL,

NOMBRE_CLIENTE VARCHAR(30) NOT NULL,

APELLIDO_CLIENTE VARCHAR(30) NOT NULL,

GENERO ENUM('M','F','I')  NOT NULL,

CELULAR VARCHAR(20) NOT NULL,

CIUDAD VARCHAR(30)  NULL,

EMAIL VARCHAR(50) NOT NULL,

CONTRASENA VARCHAR(256) NULL,

PRIMARY KEY (ID_CLIENTE)

) ENGINE = MyISAM;


CREATE TABLE facturas(

ID_FACTURA INT(4) NOT NULL,

FECHA_FACTURA DATE NOT NULL,

PRIMARY KEY (ID_FACTURA)

) ENGINE = MyISAM;


CREATE TABLE categorias_producto(

ID_CATEGORIA INT(4) NOT NULL,

NOMBRE_CATEGORIA VARCHAR(30) NOT NULL,

DESCRIPCION_CATEGORIA VARCHAR(100) NOT NULL,

PRIMARY KEY (ID_CATEGORIA)

) ENGINE = MyISAM;


CREATE TABLE proveedores(

ID_PROVEEDOR INT(4) NOT NULL,

NOMBRE_PROVEEDOR VARCHAR(30) NOT NULL,

NIT_PROVEEDOR VARCHAR(15) NOT NULL,

CIUDAD_PROVEEDOR VARCHAR(30) NOT NULL,

TELEFONO_PROVEEDOR VARCHAR(15) NOT NULL, 

PRIMARY KEY (ID_PROVEEDOR)

) ENGINE = MyISAM;


CREATE TABLE compras(

ID_COMPRA INT(4) NOT NULL,

ID_PROVEEDOR INT NOT NULL,

FECHA_COMPRA DATE NOT NULL,

TOTAL INT(8) NOT NULL,

PRIMARY KEY (ID_COMPRA)

) ENGINE = MyISAM;


CREATE TABLE productos(

ID_PRODUCTO INT(4) NOT NULL,

ID_CATEGORIA INT(4) NOT NULL,

NOMBRE_PRODUCTO VARCHAR(30) NOT NULL,

DESCRIPCION_PRODUCTO VARCHAR(100) NOT NULL,

CANTIDAD_ACTUAL INT(3) NOT NULL,

CANTIDAD_BASE  INT(3) NOT NULL,

PRIMARY KEY (ID_PRODUCTO)

) ENGINE = MyISAM;


CREATE TABLE compra_producto(

ID_PRODUCTO INT(4) NOT NULL,

ID_COMPRA INT(4) NOT NULL,

CANTIDAD_PRODUCTO INT(4) NOT NULL,

PRECIO_PRODUCTO DECIMAL(7,2) NOT NULL,

PRIMARY KEY (ID_COMPRA, ID_PRODUCTO)

) ENGINE = MyISAM;


CREATE TABLE estados_habitacion(

ID_ESTADO_HABITACION INT(4) NOT NULL,

NOMBRE_ESTADO_HABITACION VARCHAR(30) NOT NULL,

COLOR_ESTADO_HABITACION VARCHAR(12) NOT NULL,

DESCRIPCION_ESTADO_HABITACION VARCHAR(30),

PRIMARY KEY (ID_ESTADO_HABITACION)

) ENGINE = MyISAM;


CREATE TABLE habitaciones(

ID_HABITACION INT NOT NULL,

CODIGO VARCHAR(10) NOT NULL,

ID_ESTADO_HABITACION INT(4) NOT NULL, 

CAPACIDAD_HABITACION INT(4) NOT NULL,	

PRIMARY KEY (ID_HABITACION)

) ENGINE = MyISAM;


CREATE TABLE detalle_reserva(

ID_DET_RESERVA INT NOT NULL,

ID_RESERVA INT NOT NULL,

ID_HABITACION INT(4), 

PRIMARY KEY (ID_DET_RESERVA)

) ENGINE = MyISAM;


CREATE TABLE estados_reserva(

ID_ESTADO_RESERVA INT(4) NOT NULL,

NOMBRE_ESTADO_RESERVA VARCHAR(30) NOT NULL,

DESCRIPCION_ESTADO_RESERVA VARCHAR(100) NOT NULL,

PRIMARY KEY (ID_ESTADO_RESERVA)

) ENGINE = MyISAM;


CREATE TABLE tipos_reserva(

ID_TIPO_RESERVA INT(4) NOT NULL,

NOMBRE_TIPO_RESERVA VARCHAR(30) NOT NULL,

PRECIO_TIPO_RESERVA DECIMAL (10,2) NOT NULL,

PRIMARY KEY (ID_TIPO_RESERVA)

) ENGINE = MyISAM;


CREATE TABLE reservas(

ID_RESERVA INT(4) NOT NULL,

ID_CLIENTE INT(4) NOT NULL,

FECHA_RESERVA DATE NOT NULL,

ID_FACTURA INT(4)  NULL,

FECHA_INICIAL DATE NOT NULL,

FECHA_FINAL DATE NOT NULL,

ID_ESTADO_RESERVA INT(4) NOT NULL,

ID_TIPO_RESERVA INT(4) NOT NULL,

NUMERO_CAMAS_RESERVA INT(2) NOT NULL,

PRIMARY KEY (ID_RESERVA)

) ENGINE = MyISAM;


CREATE TABLE venta_producto(

ID_FACTURA INT(4) NOT NULL,

ID_PRODUCTO INT(4) NOT NULL,

CANTIDAD_PRODUCTO INT(2) NOT NULL,

PRIMARY KEY (ID_FACTURA, ID_PRODUCTO)

) ENGINE = MyISAM;


ALTER TABLE tipos_documento ADD(

CONSTRAINT TIP_UQ_NOM UNIQUE(NOMBRE_TIPO_DOCUMENTO)

);


ALTER TABLE clientes ADD(

CONSTRAINT CLI_FK_IDT FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPOS_DOCUMENTO(ID_TIPO_DOCUMENTO)

);


ALTER TABLE compras ADD(

CONSTRAINT COM_FK_IDP FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)

);


ALTER TABLE productos ADD(

CONSTRAINT PRO_FK_IDC FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS_PRODUCTO(ID_CATEGORIA)

);


ALTER TABLE compra_producto ADD(

CONSTRAINT COP_FK_IDP FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),

CONSTRAINT COP_FK_IDC FOREIGN KEY(ID_COMPRA) REFERENCES COMPRAS(ID_COMPRA)

);


ALTER TABLE habitaciones ADD(

CONSTRAINT HAB_FK_IDE FOREIGN KEY(ID_ESTADO_HABITACION) REFERENCES ESTADOS_HABITACION(ID_ESTADO_HABITACION)

);



ALTER TABLE detalle_reserva ADD(

CONSTRAINT RES_FK_IDR FOREIGN KEY (ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA),

CONSTRAINT RES_FK_ICH FOREIGN KEY (ID_HABITACION) REFERENCES HABITACIONES(ID_HABITACION)

);


ALTER TABLE reservas ADD(

CONSTRAINT RES_FK_IDC FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),

CONSTRAINT RES_FK_IDE FOREIGN KEY (ID_ESTADO_RESERVA) REFERENCES ESTADOS_RESERVA(ID_ESTADO_RESERVA),

CONSTRAINT RES_FK_IDT FOREIGN KEY (ID_TIPO_RESERVA) REFERENCES TIPOS_RESERVA(ID_TIPO_RESERVA),

CONSTRAINT RES_FK_IDF FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA)

);


ALTER TABLE venta_producto ADD(

CONSTRAINT VEP_FK_IDF FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA),

CONSTRAINT VEP_FK_IDP FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)

);

/*INSERCION TIPO DE DOCUMENTO*/
INSERT INTO `hoteldb`.`tipos_documento` (`ID_TIPO_DOCUMENTO`, `NOMBRE_TIPO_DOCUMENTO`) VALUES ('1', 'CEDULA');
INSERT INTO `hoteldb`.`tipos_documento` (`ID_TIPO_DOCUMENTO`, `NOMBRE_TIPO_DOCUMENTO`) VALUES ('2', 'PASAPORTE');
INSERT INTO `hoteldb`.`tipos_documento` (`ID_TIPO_DOCUMENTO`, `NOMBRE_TIPO_DOCUMENTO`) VALUES ('3', 'CEDULA EXTRANJERA');

INSERT INTO `hoteldb`.`clientes` (`ID_CLIENTE`, `ID_TIPO_DOCUMENTO`, `DOCUMENTO_CLIENTE`, `NOMBRE_CLIENTE`, `APELLIDO_CLIENTE`, `GENERO`, `CELULAR`, `CIUDAD`, `EMAIL`) VALUES ('1', '1', '5413213', 'FELIPE', 'GONZALEZ', 'M', '1321312', 'BOGOTA', 'DSADAD@DASD.COM');
INSERT INTO `hoteldb`.`clientes` (`ID_CLIENTE`, `ID_TIPO_DOCUMENTO`, `DOCUMENTO_CLIENTE`, `NOMBRE_CLIENTE`, `APELLIDO_CLIENTE`, `GENERO`, `CELULAR`, `CIUDAD`, `EMAIL`) VALUES ('2', '1', '45413244', 'LEO', 'BONILLA', 'M', '1231564', 'BOGOTA', 'DSADAD@DASD.COM');
INSERT INTO `hoteldb`.`clientes` (`ID_CLIENTE`, `ID_TIPO_DOCUMENTO`, `DOCUMENTO_CLIENTE`, `NOMBRE_CLIENTE`, `APELLIDO_CLIENTE`, `GENERO`, `CELULAR`, `CIUDAD`, `EMAIL`) VALUES ('3', '1', '562134654', 'JOSE', 'MENDEZ', 'M', '1321465', 'BOGOTA', 'DSADAD@DASD.COM');
INSERT INTO `hoteldb`.`clientes` (`ID_CLIENTE`, `ID_TIPO_DOCUMENTO`, `DOCUMENTO_CLIENTE`, `NOMBRE_CLIENTE`, `APELLIDO_CLIENTE`, `GENERO`, `CELULAR`, `CIUDAD`, `EMAIL`) VALUES ('4', '1', '44654654', 'ANDRES', 'GOMEZ', 'M', '665464', 'BOGOTA', 'DSADAD@DASD.COM');

/*INSERCION CATEGORIAS DE PRODUCTO*/
INSERT INTO `hoteldb`.`categorias_producto` (`ID_CATEGORIA`, `NOMBRE_CATEGORIA`, `DESCRIPCION_CATEGORIA`) VALUES ('1', 'CONSUMIBLES', 'PRODUCTOS PERECEDEROS');
INSERT INTO `hoteldb`.`categorias_producto` (`ID_CATEGORIA`, `NOMBRE_CATEGORIA`, `DESCRIPCION_CATEGORIA`) VALUES ('2', 'NO CONSUMIBLES', 'PRODUCTOS NO PERECEDEROS');

/*INSERCION DE PRODUCTOS*/
INSERT INTO `hoteldb`.`productos` (`ID_PRODUCTO`, `ID_CATEGORIA`, `NOMBRE_PRODUCTO`, `DESCRIPCION_PRODUCTO`, `CANTIDAD_ACTUAL`, `CANTIDAD_BASE`) VALUES ('1', '2', 'JABON', 'PRODUCTO DE LIMPIEZA', '0', '10');
INSERT INTO `hoteldb`.`productos` (`ID_PRODUCTO`, `ID_CATEGORIA`, `NOMBRE_PRODUCTO`, `DESCRIPCION_PRODUCTO`, `CANTIDAD_ACTUAL`, `CANTIDAD_BASE`) VALUES ('2', '1', 'JAMON', 'PRODUCTO COMESTIBLE', '0', '10');


/*INSERCION PROVEDORES*/
INSERT INTO `hoteldb`.`proveedores` (`ID_PROVEEDOR`, `NOMBRE_PROVEEDOR`, `NIT_PROVEEDOR`, `CIUDAD_PROVEEDOR`, `TELEFONO_PROVEEDOR`) VALUES ('1', 'PROVEDOR 1', '4654', 'TUNJA', '3321321321');
INSERT INTO `hoteldb`.`proveedores` (`ID_PROVEEDOR`, `NOMBRE_PROVEEDOR`, `NIT_PROVEEDOR`, `CIUDAD_PROVEEDOR`, `TELEFONO_PROVEEDOR`) VALUES ('2', 'PROVEDOR 2', '5465487', 'BOGOTA', '56465446');
INSERT INTO `hoteldb`.`proveedores` (`ID_PROVEEDOR`, `NOMBRE_PROVEEDOR`, `NIT_PROVEEDOR`, `CIUDAD_PROVEEDOR`, `TELEFONO_PROVEEDOR`) VALUES ('3', 'PROVEDOR 3', '54564', 'TUNJA', '65465464654');
INSERT INTO `hoteldb`.`proveedores` (`ID_PROVEEDOR`, `NOMBRE_PROVEEDOR`, `NIT_PROVEEDOR`, `CIUDAD_PROVEEDOR`, `TELEFONO_PROVEEDOR`) VALUES ('4', 'PROVEDOR 4', '23121', 'BOGOTA', '6546545644');
INSERT INTO `hoteldb`.`proveedores` (`ID_PROVEEDOR`, `NOMBRE_PROVEEDOR`, `NIT_PROVEEDOR`, `CIUDAD_PROVEEDOR`, `TELEFONO_PROVEEDOR`) VALUES ('5', 'PROVEDOR 5', '2311321', 'TUNJA', '4654654654');
INSERT INTO `hoteldb`.`proveedores` (`ID_PROVEEDOR`, `NOMBRE_PROVEEDOR`, `NIT_PROVEEDOR`, `CIUDAD_PROVEEDOR`, `TELEFONO_PROVEEDOR`) VALUES ('6', 'PROVEDOR 6', '321321', 'BOGOTA', '4654654654');
INSERT INTO `hoteldb`.`proveedores` (`ID_PROVEEDOR`, `NOMBRE_PROVEEDOR`, `NIT_PROVEEDOR`, `CIUDAD_PROVEEDOR`, `TELEFONO_PROVEEDOR`) VALUES ('7', 'PROVEDOR 7', '3213213', 'TUNJA', '');

/*INSERCION DE TIPO RESERVA*/

INSERT INTO `hoteldb`.`tipos_reserva` (ID_TIPO_RESERVA, NOMBRE_TIPO_RESERVA, PRECIO_TIPO_RESERVA) VALUES (1, 'INDIVIDUAL', 15000);
INSERT INTO `hoteldb`.`tipos_reserva` (ID_TIPO_RESERVA, NOMBRE_TIPO_RESERVA, PRECIO_TIPO_RESERVA) VALUES (2, 'COMPARTIDA', 50000);

/*ESTADOS DE LA HABITACION*/
INSERT INTO `hoteldb`.`estados_habitacion` (`ID_ESTADO_HABITACION`, `NOMBRE_ESTADO_HABITACION`, `COLOR_ESTADO_HABITACION`, `DESCRIPCION_ESTADO_HABITACION`) VALUES ('1', 'LIMPIA', 'V', 'HABITACION LISTA PARA SERVICIO');
INSERT INTO `hoteldb`.`estados_habitacion` (`ID_ESTADO_HABITACION`, `NOMBRE_ESTADO_HABITACION`, `COLOR_ESTADO_HABITACION`, `DESCRIPCION_ESTADO_HABITACION`) VALUES ('2', 'SIN LIMPIAR', 'C', 'HABITACION SIN LIMPIAR');
INSERT INTO `hoteldb`.`estados_habitacion` (`ID_ESTADO_HABITACION`, `NOMBRE_ESTADO_HABITACION`, `COLOR_ESTADO_HABITACION`, `DESCRIPCION_ESTADO_HABITACION`) VALUES ('3', 'MANTENIMIENTO', 'R', 'HABITACION FUERA DE SERVICIO');
INSERT INTO `hoteldb`.`estados_habitacion` (`ID_ESTADO_HABITACION`, `NOMBRE_ESTADO_HABITACION`, `COLOR_ESTADO_HABITACION`, `DESCRIPCION_ESTADO_HABITACION`) VALUES ('4', 'OCUPADA', 'A', 'HABITACION OCUPADA');

/*DATOS HOTEL*/
INSERT INTO `hoteldb`.`info_hotel` (`ID_INFO`, `NOMBRE_HOTEL`, `TELEFONO_HOTEL`, `EMAIL_HOTEL`, `RAZON_SOCIAL`, `NIF`, `DEPARTAMENTO_HOTEL`, `MUNICIPIO_HOTEL`, `DIRECCION_HOTEL`) VALUES ('1', 'YEIMAR', '321231213', 'YEIMAR@HOTMAIL.COM', 'ESTAMOS PARA SERVIR', '23232', 'BOYACA', 'TUTA', 'KILOMETRO 10 VIA PAIPA');


/*  INSERCION HABITACION*/
INSERT INTO `hoteldb`.`habitaciones` (`ID_HABITACION`, `CODIGO`, `ID_ESTADO_HABITACION`, `CAPACIDAD_HABITACION`) VALUES ('1', 'H001', '1', '5');
INSERT INTO `hoteldb`.`habitaciones` (`ID_HABITACION`, `CODIGO`, `ID_ESTADO_HABITACION`, `CAPACIDAD_HABITACION`) VALUES ('2', 'H002', '1', '5');
INSERT INTO `hoteldb`.`habitaciones` (`ID_HABITACION`, `CODIGO`, `ID_ESTADO_HABITACION`, `CAPACIDAD_HABITACION`) VALUES ('3', 'H003', '1', '5');
INSERT INTO `hoteldb`.`habitaciones` (`ID_HABITACION`, `CODIGO`, `ID_ESTADO_HABITACION`, `CAPACIDAD_HABITACION`) VALUES ('4', 'H004', '1', '5');
INSERT INTO `hoteldb`.`habitaciones` (`ID_HABITACION`, `CODIGO`, `ID_ESTADO_HABITACION`, `CAPACIDAD_HABITACION`) VALUES ('5', 'H005', '1', '5');
INSERT INTO `hoteldb`.`habitaciones` (`ID_HABITACION`, `CODIGO`, `ID_ESTADO_HABITACION`, `CAPACIDAD_HABITACION`) VALUES ('6', 'H006', '1', '5');
INSERT INTO `hoteldb`.`habitaciones` (`ID_HABITACION`, `CODIGO`, `ID_ESTADO_HABITACION`, `CAPACIDAD_HABITACION`) VALUES ('7', 'H007', '1', '5');

/*ESTADOS DE RESERVA*/
INSERT INTO `hoteldb`.`estados_reserva` (`ID_ESTADO_RESERVA`, `NOMBRE_ESTADO_RESERVA`, `DESCRIPCION_ESTADO_RESERVA`) VALUES ('1', 'SIN ASINAR', 'LA RESERVA AUN NO ESTA CONFIRMADA');
INSERT INTO `hoteldb`.`estados_reserva` (`ID_ESTADO_RESERVA`, `NOMBRE_ESTADO_RESERVA`, `DESCRIPCION_ESTADO_RESERVA`) VALUES ('2', 'CONFIRMADA', 'LA RESERVA ESTA CONFIRMADA');
INSERT INTO `hoteldb`.`estados_reserva` (`ID_ESTADO_RESERVA`, `NOMBRE_ESTADO_RESERVA`, `DESCRIPCION_ESTADO_RESERVA`) VALUES ('3', 'EN ESTANCIA', 'EL HUESPED ESTA EN EL HOTEL');
INSERT INTO `hoteldb`.`estados_reserva` (`ID_ESTADO_RESERVA`, `NOMBRE_ESTADO_RESERVA`, `DESCRIPCION_ESTADO_RESERVA`) VALUES ('4', 'CANCELADA', 'LA RESERVA FUE CANCELDA');
INSERT INTO `hoteldb`.`estados_reserva` (`ID_ESTADO_RESERVA`, `NOMBRE_ESTADO_RESERVA`, `DESCRIPCION_ESTADO_RESERVA`) VALUES ('5', 'TERMINADA', 'LA RESERVA YA TERMINO');

commit;